version: "3.8"

services:
  ckeeper-agent:
    image: europe-west1-docker.pkg.dev/pigen-463612/devops-agent-artifact/devops-agent:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: "ckeeper-test-bot"
        GIT_USER_EMAIL: "1472998+ckeeper-test-bot@users.noreply.github.com"
    ports:
      - "8000:8000"
    container_name: ckeeper-agent
    environment:
      - GIT_USER_NAME=ckeeper-test-bot
      - GIT_USER_EMAIL=1472998+ckeeper-test-bot@users.noreply.github.com