version: "3.8"

services:
  ckeeper-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUBAPP_USER_NAME: "ckeeper-bot-dev"
        GITHUBAPP_USER_EMAIL: "1510035+ckeeper-bot-dev@users.noreply.github.com"
    ports:
      - "8000:8000"
    container_name: ckeeper-agent
    environment:
      - GITHUBAPP_USER_NAME=ckeeper-bot-dev
      - GITHUBAPP_USER_EMAIL=1510035+ckeeper-bot-dev@users.noreply.github.com
    networks:
      - evaluation-network

networks:
  evaluation-network:
    external: true